config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[show]
  root 'posts#index'
  scope module: :users do
    resources :posts, only: %i[new create edit update destroy]
    resources :relationships, only: %i[create destroy]
    resource :following_posts, only: %i[show]
    resource :profile, only: %i[show edit update]
  end
  resources :posts, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140 }
  scope :default_order, -> { order(:id) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'following_id', dependent: :destroy, inverse_of: 'following'
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy, inverse_of: 'followers'
  has_many :followings, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following
  validates :name, presence: true, format: { with: /\A[a-zA-Z]+\z/ }, length: { maximum: 20 }

  def follow(user_id)
    active_relationships.create(follower_id: user_id)
  end

  def unfollow!(user_id)
    active_relationships.find_by(follower_id: user_id).destroy!
  end

  def following?(user)
    followings.exists?(user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @posts = Post.default_order
  end

  def show; end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users/following_posts_controller.rb
class Users::FollowingPostsController < ApplicationController
  def show
    @posts = Post.where(user_id: current_user.following_ids)
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_path, notice: t('controllers.common.created', model: '投稿')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: t('controllers.common.updated', model: '投稿'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, notice: t('controllers.common.destroyed', model: '投稿'), status: :see_other
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :set_user

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('controllers.common.updated', model: 'プロフィール'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:biography, :blog_url)
  end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:follower_id])
    redirect_to request.referer || root_path
  end

  def destroy
    user = Relationship.find(params[:id]).follower
    current_user.unfollow!(user.id)
    redirect_to request.referer || root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :redirect_profile_path_if_current_user

  def show; end

  def set_user
    @user = User.find(params[:id])
  end

  # ポスト一覧画面から自分のプロフィールリンクをクリックすると、自分のプロフィールページに遷移
  def redirect_profile_path_if_current_user
    redirect_to profile_path if current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_alert_helper.rb
module BootstrapAlertHelper
  def bootstrap_alert_class_for(key)
    case key
    when 'alert'
      'warning'
    when 'notice'
      'success'
    when 'error'
      'danger'
    else
      'info'
    end
  end
end

app/views/layouts/_flash.html.haml
.notification
  - flash.each do |key, value|
    .alert{ class: "alert-#{bootstrap_alert_class_for(key)}" }= value

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-body-tertiary
  .container
    %ul.navbar-nav
      %li.nav-item
        = link_to 'Miniblog', root_path, class: 'navbar-brand fs-2'
      %li.nav-item
        = link_to 'プロフィール', profile_path, class: 'nav-link'
    %ul.navbar-nav
      - if user_signed_in?
        %li.nav-item
          = link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-outline-danger'
      - else
        %li.nav-item
          = link_to 'ログイン', new_user_session_path, class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Miniblog
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags
  %body
    = render 'layouts/header'
    .container-md.pt-4
      = render 'layouts/flash'
      = yield

app/views/posts/index.html.haml
= link_to '新規投稿', new_post_path, class: 'btn btn-primary mt-4'
= link_to 'フォロー中のユーザーの投稿', following_posts_path, class: 'btn btn-success mt-4'
= render 'users/shared/posts', posts: @posts

app/views/posts/show.html.haml
.card.mb-4
  .card-body
    .card-text
      = @post.content

- if @post.user == current_user
  = link_to '編集', edit_post_path(@post), class: 'btn btn-success'
  = button_to '削除', post_path(@post), method: :delete, class: 'btn btn-danger mt-4'

app/views/users/following_posts/show.html.haml
= render 'users/shared/posts', posts: @posts

app/views/users/posts/_form.html.haml
= simple_form_for post do |f|
  - if post.errors.any?
    %ul
      - post.errors.full_messages.each do |message|
        %li= message
  = f.input :content, placeholder: '文章を入力してください'
  = f.button :submit, class: 'btn btn-primary'

app/views/users/posts/edit.html.haml
= render 'form', post: @post

app/views/users/posts/new.html.haml
= render 'form', post: @post

app/views/users/profiles/edit.html.haml
= simple_form_for @user, url: profile_path do |f|
  - if @user.errors.any?
    %ul
      - @user.errors.full_messages.each do |message|
        %li= message
  = f.input :biography, placeholder: '自己紹介を入力してください'
  = f.url_field :blog_url, as: :url, placeholder: 'ブログのURLを入力'
  = f.button :submit, class: 'btn btn-primary'

app/views/users/profiles/show.html.haml
%h1.h3 プロフィール

= render 'users/shared/user_profile', user: @user, editable: true

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to 'ログイン', new_session_path(resource_name), class: 'btn btn-success mt-3'
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to '新規登録', new_registration_path(resource_name), class: 'btn btn-success mt-3'

app/views/users/shared/_posts.html.haml
.d-grid.row-gap-4.mt-4
  - posts.each do |post|
    .card.shadow.mx-4
      .card-body
        .card-text
          = link_to post.content, post_path(post), class: 'text-decoration-none text-body'
        .footer-text.text-end
          - if user_signed_in? && current_user != post.user
            - if current_user.following?(post.user)
              = button_to 'フォロー解除', relationship_path(current_user.active_relationships.find_by(follower_id: post.user.id)), class: 'btn btn-danger', method: :delete
            - else
              = button_to 'フォロー', relationships_path(follower_id: post.user), class: 'btn btn-primary'
          = link_to post.user.name, user_path(post.user), class: 'text-decoration-none text-body'

app/views/users/shared/_user_profile.html.haml
- editable ||= false
.row.justify-content-center
  .col-md-8
    .card
      .card-body
        .card-title
          %h1.h3= user.name
        .card-text
          .email= user.email
          .biography= user.biography
          .blog_url= user.blog_url
      - if editable
        .card-footer
          = link_to '編集', edit_profile_path, class: 'btn btn-success mt-3'

app/views/users/show.html.haml
= render 'users/shared/user_profile', user: @user